/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package101;

import javax.swing.ImageIcon;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aravind
 */
public class GuitarFrame extends javax.swing.JFrame {

    int notes[]=new int[7];
    String outChar[]=new String[7];
    String fretnum="";
    String s="";
    ImageIcon icon=new ImageIcon("dot.png");
    
    /**
     * Creates new form NewJFrame1
     */
    public GuitarFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        s21 = new javax.swing.JLabel();
        s31 = new javax.swing.JLabel();
        s41 = new javax.swing.JLabel();
        s51 = new javax.swing.JLabel();
        s61 = new javax.swing.JLabel();
        s12 = new javax.swing.JLabel();
        s22 = new javax.swing.JLabel();
        s32 = new javax.swing.JLabel();
        s42 = new javax.swing.JLabel();
        s52 = new javax.swing.JLabel();
        s62 = new javax.swing.JLabel();
        s13 = new javax.swing.JLabel();
        s23 = new javax.swing.JLabel();
        s33 = new javax.swing.JLabel();
        s43 = new javax.swing.JLabel();
        s53 = new javax.swing.JLabel();
        s63 = new javax.swing.JLabel();
        s14 = new javax.swing.JLabel();
        s24 = new javax.swing.JLabel();
        s34 = new javax.swing.JLabel();
        s44 = new javax.swing.JLabel();
        s54 = new javax.swing.JLabel();
        s64 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        s11 = new javax.swing.JLabel();
        out1 = new javax.swing.JLabel();
        out2 = new javax.swing.JLabel();
        out3 = new javax.swing.JLabel();
        out4 = new javax.swing.JLabel();
        out5 = new javax.swing.JLabel();
        out6 = new javax.swing.JLabel();
        fretNum = new javax.swing.JLabel();
        chdName = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 40, 46));

        s31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 40, 46));

        s41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 40, 46));

        s51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s51, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 40, 46));

        s61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s61, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 40, 46));

        s12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 40, 46));

        s22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 40, 46));

        s32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s32, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 40, 46));

        s42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s42, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 40, 46));

        s52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s52, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 40, 46));

        s62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s62, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 40, 46));

        s13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 40, 46));

        s23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 40, 46));

        s33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 40, 46));

        s43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s43, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 40, 46));

        s53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s53, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 40, 46));

        s63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s63, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 40, 46));

        s14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 40, 46));

        s24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 40, 46));

        s34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s34, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 40, 46));

        s44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s44, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 40, 46));

        s54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s54, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 40, 46));

        s64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(s64, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 40, 46));

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 5));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOpaque(true);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOpaque(true);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOpaque(true);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOpaque(true);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setOpaque(true);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 202));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setOpaque(true);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 202));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setOpaque(true);
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 202));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator9.setOpaque(true);
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 202));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator10.setOpaque(true);
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 202));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator11.setOpaque(true);
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 202));

        s11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(s11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 40, 46));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        out1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        out1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        out1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(out1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 40, 40));

        out2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        out2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        out2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(out2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 40, 40));

        out3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        out3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        out3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(out3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 40, 40));

        out4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        out4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        out4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(out4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 40, 40));

        out5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        out5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        out5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(out5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 40, 40));

        out6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        out6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        out6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(out6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 40, 40));

        fretNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fretNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(fretNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 30, 30));

        chdName.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        chdName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(chdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 320, 310));

        jComboBox1.setBackground(new java.awt.Color(0, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<html><i>Select Note", "C", "D", "E", "F", "G", "A", "B" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 100, -1));

        jComboBox2.setBackground(new java.awt.Color(0, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "b " }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 50, -1));

        jComboBox3.setBackground(new java.awt.Color(0, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<html><i>Select Chord", " ", "m", "6", "7", "9", "m6", "m7", "maj7", "dim", "+", "sus" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 110, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Show Chord");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 140, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package101/home.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 30, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package101/guitar.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 230, 170));

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem()=="C"||jComboBox1.getSelectedItem()=="F")
            jComboBox2.setEnabled(false);
        else
            jComboBox2.setEnabled(true);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resetPad();
        s=jComboBox1.getSelectedItem().toString()+jComboBox2.getSelectedItem().toString()+
                jComboBox3.getSelectedItem().toString();
        chdName.setText("<html><i>"+s);
        getChord();
        displayChord();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new StartFrame().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    public void getChord(){
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/Music101DB","root","aravind123");
            Statement st=con.createStatement();
            String query="SELECT * from gchords where ChordName=\""+s+"\";";
            ResultSet rs=st.executeQuery(query);
            while(rs.next()){
                notes[1]=rs.getInt("one");
                notes[2]=rs.getInt("two");
                notes[3]=rs.getInt("three");
                notes[4]=rs.getInt("four");
                notes[5]=rs.getInt("five");
                notes[6]=rs.getInt("six");
                outChar[1]=rs.getString("outone");
                outChar[2]=rs.getString("outtwo");
                outChar[3]=rs.getString("outthree");
                outChar[4]=rs.getString("outfour");
                outChar[5]=rs.getString("outfive");
                outChar[6]=rs.getString("outsix");
                fretnum=rs.getString("fretnum");
            }           
        } catch (SQLException ex) {
            Logger.getLogger(GuitarFrame.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }
    
    public void displayChord(){
        /*for(int z = 0; z < 7; z++){
            System.out.println(notes[z]);
            System.out.println(outChar[z]);
        }
            System.out.println(fretnum);*/
            
            
        switch(notes[1]){
            case 0:
                break;
            case 1:
                s11.setIcon(icon);
                break;
            case 2:
                s12.setIcon(icon);
                break;
            case 3:
                s13.setIcon(icon);
                break;
            case 4:
                s14.setIcon(icon);
                break;    
        }
        switch(notes[2]){
            case 0:
                break;
            case 1:
                s21.setIcon(icon);
                break;
            case 2:
                s22.setIcon(icon);
                break;
            case 3:
                s23.setIcon(icon);
                break;
            case 4:
                s24.setIcon(icon);
                break;    
        }
        switch(notes[3]){
            case 0:
                break;
            case 1:
                s31.setIcon(icon);
                break;
            case 2:
                s32.setIcon(icon);
                break;
            case 3:
                s33.setIcon(icon);
                break;
            case 4:
                s34.setIcon(icon);
                break;    
        }
        switch(notes[4]){
            case 0:
                break;
            case 1:
                s41.setIcon(icon);
                break;
            case 2:
                s42.setIcon(icon);
                break;
            case 3:
                s43.setIcon(icon);
                break;
            case 4:
                s44.setIcon(icon);
                break;    
        }
        switch(notes[5]){
            case 0:
                break;
            case 1:
                s51.setIcon(icon);
                break;
            case 2:
                s52.setIcon(icon);
                break;
            case 3:
                s53.setIcon(icon);
                break;
            case 4:
                s54.setIcon(icon);
                break;    
        }
        switch(notes[6]){
            case 0:
                break;
            case 1:
                s61.setIcon(icon);
                break;
            case 2:
                s62.setIcon(icon);
                break;
            case 3:
                s63.setIcon(icon);
                break;
            case 4:
                s64.setIcon(icon);
                break;    
        }
        out1.setText(outChar[1]);
        out2.setText(outChar[2]);
        out3.setText(outChar[3]);
        out4.setText(outChar[4]);
        out5.setText(outChar[5]);
        out6.setText(outChar[6]);
        fretNum.setText(fretnum);
    }
    
    public void resetPad(){
        s11.setIcon(null);
        s12.setIcon(null);
        s13.setIcon(null);
        s14.setIcon(null);
        s21.setIcon(null);
        s22.setIcon(null);
        s23.setIcon(null);
        s24.setIcon(null);
        s31.setIcon(null);
        s32.setIcon(null);
        s33.setIcon(null);
        s34.setIcon(null);
        s41.setIcon(null);
        s42.setIcon(null);
        s43.setIcon(null);
        s44.setIcon(null);
        s51.setIcon(null);
        s52.setIcon(null);
        s53.setIcon(null);
        s54.setIcon(null);
        s61.setIcon(null);
        s62.setIcon(null);
        s63.setIcon(null);
        s64.setIcon(null);
        out1.setText(null);
        out2.setText(null);
        out3.setText(null);
        out4.setText(null);
        out5.setText(null);
        out6.setText(null);
        fretNum.setText(null);
        for(int i=1;i<7;i++){
            notes[i]=0;
            outChar[i]="";
        }
        fretnum="";
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuitarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuitarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuitarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuitarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuitarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chdName;
    private javax.swing.JLabel fretNum;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel out1;
    private javax.swing.JLabel out2;
    private javax.swing.JLabel out3;
    private javax.swing.JLabel out4;
    private javax.swing.JLabel out5;
    private javax.swing.JLabel out6;
    private javax.swing.JLabel s11;
    private javax.swing.JLabel s12;
    private javax.swing.JLabel s13;
    private javax.swing.JLabel s14;
    private javax.swing.JLabel s21;
    private javax.swing.JLabel s22;
    private javax.swing.JLabel s23;
    private javax.swing.JLabel s24;
    private javax.swing.JLabel s31;
    private javax.swing.JLabel s32;
    private javax.swing.JLabel s33;
    private javax.swing.JLabel s34;
    private javax.swing.JLabel s41;
    private javax.swing.JLabel s42;
    private javax.swing.JLabel s43;
    private javax.swing.JLabel s44;
    private javax.swing.JLabel s51;
    private javax.swing.JLabel s52;
    private javax.swing.JLabel s53;
    private javax.swing.JLabel s54;
    private javax.swing.JLabel s61;
    private javax.swing.JLabel s62;
    private javax.swing.JLabel s63;
    private javax.swing.JLabel s64;
    // End of variables declaration//GEN-END:variables
}
